# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Test
  jobs: 
  - job: dotnetTestAgent
    steps:
    - script: dotnet test
      displayName: Time to test it!

- stage: Build
  dependsOn: Test
  jobs: 
  - job: buildWindows
    steps:
    - script: dotnet publish -c Release -r win10-x64
      displayName: Time to publish it!
  - job: buildLinux
    steps:
    - script: dotnet publish -c Release -r linux-x64
      displayName: Time to publish it!