# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: StageTest
  jobs:
  - job: JobTest
    steps:
    - script: dotnet test
      displayName: 'Running tests'

- stage: StageBuild
  dependsOn: StageTest
  jobs:
  - job: JobBuildWindows
    steps:
    - script: dotnet publish -c Release -r win10-x64
      displayName: 'Building Windows version'
  
  - job: JobBuildLinux
    steps:
    - script: dotnet publish -c Release -r linux-x64
      displayName: 'Building Linux version'
